[features]
seeds = false
skip-lint = false
#[programs.devnet]
#zkme_sol =

[programs.mainnet]
zkme_sol = ""

[registry]
#url = "https://api.apr.dev"
#url = "http://127.0.0.1:8899"
url = "https://api.mainnet-beta.solana.com"

[provider]
cluster = "Mainnet"
wallet = ""

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
